version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
  - package-ecosystem: "pip"
    directory: "/ledfx-beta"
    schedule:
      interval: daily
      time: "06:00"
  - package-ecosystem: "pip"
    directory: "/ledfx-beta-vban"
    schedule:
      interval: daily
      time: "06:00"
